# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            G4DB
tagline:          'A Jekyll theme'
description:      'Keeping All the Good Ones.'
url:              Blackboar4all.github.io
baseurl:          /

author:
  name:           'Jiho Choi'
  url:           -

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
